# Generated by Django 5.1.4 on 2024-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='module',
            field=models.CharField(choices=[('module1', 'Module 1: Introduction to Python'), ('module2', 'Module 2: Advanced JavaScript'), ('module3', 'Module 3: Data Structures in Java'), ('module4', 'Module 4: C++ for Game Development'), ('module5', 'Module 5: Ruby on Rails')], default='module1', help_text='The module the student is booking.', max_length=100),
        ),
    ]
