# Generated by Django 5.1.2 on 2024-12-12 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_studentrequest_admin_reply_studentrequest_replied_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(help_text="The text of the admin's reply.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tutorials.studentrequest')),
            ],
        ),
    ]
